# Generated by Django 2.0.4 on 2018-04-12 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='car',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
