# Generated by Django 2.0.4 on 2018-04-13 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0003_auto_20180413_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_driver',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
