# Generated by Django 2.0.4 on 2018-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0005_auto_20180413_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_driver',
            field=models.NullBooleanField(),
        ),
    ]
