# Generated by Django 2.0.4 on 2018-04-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0007_auto_20180413_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
