# Generated by Django 2.0.4 on 2018-04-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0010_auto_20180413_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SET_BY_DRIVER', 'set by driver'), ('SET_BY_PASSENGER', 'set by passenger'), ('ACCEPTED', 'accepted'), ('COMPLETED', 'completed')], max_length=20)),
                ('start_data', models.DateField()),
                ('pickup_longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pickup_latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dropoff_longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dropoff_latitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides_handling.Profile')),
            ],
        ),
    ]
