# Generated by Django 2.0.4 on 2018-04-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0011_ride'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='start_data',
            new_name='pickup_datetime',
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_count',
            field=models.IntegerField(default=1),
        ),
    ]
