# Generated by Django 2.0.4 on 2018-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0012_auto_20180420_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='dropoff_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ride',
            name='dropoff_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
