# Generated by Django 2.0.4 on 2018-04-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0014_auto_20180422_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('SET_BY_DRIVER', 'Set by driver'), ('SET_BY_PASSENGER', 'Set by passenger'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], max_length=20),
        ),
    ]
