# Generated by Django 2.0.4 on 2018-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0015_auto_20180423_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='estimated_trip_time',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
