# Generated by Django 2.0.4 on 2018-05-12 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0015_auto_20180423_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='rides_handling.Profile'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('SET_BY_PASSENGER', 'Set by passenger'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], max_length=20),
        ),
    ]
