# Generated by Django 2.0.4 on 2018-05-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0016_ride_estimated_trip_time'),
        ('rides_handling', '0018_auto_20180512_0937'),
    ]

    operations = [
    ]
