# Generated by Django 2.0.4 on 2018-05-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0019_auto_20180512_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
    ]
