# Generated by Django 2.0.4 on 2018-05-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0024_auto_20180512_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='grade_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='grade_sum',
            field=models.IntegerField(default=0),
        ),
    ]
