# Generated by Django 2.0.4 on 2018-05-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0025_auto_20180522_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='grade_counter',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='grade_sum',
        ),
        migrations.AddField(
            model_name='profile',
            name='grade_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='grade_sum',
            field=models.IntegerField(default=0),
        ),
    ]
