# Generated by Django 2.0.4 on 2018-05-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0019_auto_20180514_1703'),
        ('rides_handling', '0026_auto_20180522_1800'),
    ]

    operations = [
    ]
