# Generated by Django 2.0.4 on 2018-05-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides_handling', '0031_auto_20180528_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='ride',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
